### ISSUE TITLE
Sugestão de melhoria

### ISSUE THREAD

**Issue by All3yp** [MagnoCarta/UriScrapping#5]
Seria bom colocar no README como conseguirmos rodar como script bash. Tivemos um pouquinho de dificuldade, assim, poderíamos utilizar melhor dos recursos do código. 

By: Bash News.

**Comment by MagnoCarta** [comment]
Obg e desculpa, corrigi esse problema e ainda fiz melhorias, seu feedback ajudou me a melhorar o código ! :)
